### PR TITLE
Downgrade to ForgeGradle 2.3 & Gradle 3.1 to fix Openj9 support

### PR DESCRIPTION
**Pull request by Rishum-P**
The update to ForgeGradle 3 removed OpenJ9 Support. This downgrades the build script back to the previous one, which makes the mod compatible with OpenJ9 for the few people that use it.

### CODE REVIEW

**Comment by Sollace** [comment]
Instead of adding a lib folder, why can't people download the other repos and push them to their local maven with `gradlew build publishToMavenLocal`?

**Comment by Rishum-P** [comment]
This was more about fixing OpenJ9 support. That never worked with the old Build Script as it was missing Maven local. I've changed that now.

**Comment by KorewaLidesu** [comment]
> Instead of adding a lib folder, why can't people download the other repos and push them to their local maven with `gradlew build publishToMavenLocal`?

Instead of download other repos why not just use Jitpack

**Comment by Rishum-P** [comment]
Tested and confirmed that OpenJ9 support is now fixed in #495. 
This is now not needed.

**Pull request closed without merging**
